//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication9.ie.jobs.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JobWSSoap", Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchJobsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobDisplayOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExpireJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefreshJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndustriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobRegionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressRegionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmployerStatsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JobWS() {
            this.Url = global::WebApplication9.Properties.Settings.Default.WebApplication9_ie_jobs_www_JobWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchJobsCompletedEventHandler SearchJobsCompleted;
        
        /// <remarks/>
        public event GetJobDisplayCompletedEventHandler GetJobDisplayCompleted;
        
        /// <remarks/>
        public event ExpireJobCompletedEventHandler ExpireJobCompleted;
        
        /// <remarks/>
        public event PostJobCompletedEventHandler PostJobCompleted;
        
        /// <remarks/>
        public event UpdateJobCompletedEventHandler UpdateJobCompleted;
        
        /// <remarks/>
        public event RefreshJobCompletedEventHandler RefreshJobCompleted;
        
        /// <remarks/>
        public event AddApplicationCompletedEventHandler AddApplicationCompleted;
        
        /// <remarks/>
        public event GetJobCategoriesCompletedEventHandler GetJobCategoriesCompleted;
        
        /// <remarks/>
        public event GetIndustriesCompletedEventHandler GetIndustriesCompleted;
        
        /// <remarks/>
        public event GetJobRegionsCompletedEventHandler GetJobRegionsCompleted;
        
        /// <remarks/>
        public event GetCountriesCompletedEventHandler GetCountriesCompleted;
        
        /// <remarks/>
        public event GetAddressRegionsCompletedEventHandler GetAddressRegionsCompleted;
        
        /// <remarks/>
        public event GetEmployerStatsCompletedEventHandler GetEmployerStatsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/SearchJobs", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public JobListItem[] SearchJobs(int[] employerIds, int[] jobCategoryIds, int[] regionIds, bool excludeAgencies, int[] industryIds, JobDuration jobType, JobHours jobHours, string keywords, System.DateTime fromDate, System.DateTime toDate, int startRecord, int pageSize, string key, out int recordCount) {
            object[] results = this.Invoke("SearchJobs", new object[] {
                        employerIds,
                        jobCategoryIds,
                        regionIds,
                        excludeAgencies,
                        industryIds,
                        jobType,
                        jobHours,
                        keywords,
                        fromDate,
                        toDate,
                        startRecord,
                        pageSize,
                        key});
            recordCount = ((int)(results[1]));
            return ((JobListItem[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchJobsAsync(int[] employerIds, int[] jobCategoryIds, int[] regionIds, bool excludeAgencies, int[] industryIds, JobDuration jobType, JobHours jobHours, string keywords, System.DateTime fromDate, System.DateTime toDate, int startRecord, int pageSize, string key) {
            this.SearchJobsAsync(employerIds, jobCategoryIds, regionIds, excludeAgencies, industryIds, jobType, jobHours, keywords, fromDate, toDate, startRecord, pageSize, key, null);
        }
        
        /// <remarks/>
        public void SearchJobsAsync(int[] employerIds, int[] jobCategoryIds, int[] regionIds, bool excludeAgencies, int[] industryIds, JobDuration jobType, JobHours jobHours, string keywords, System.DateTime fromDate, System.DateTime toDate, int startRecord, int pageSize, string key, object userState) {
            if ((this.SearchJobsOperationCompleted == null)) {
                this.SearchJobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchJobsOperationCompleted);
            }
            this.InvokeAsync("SearchJobs", new object[] {
                        employerIds,
                        jobCategoryIds,
                        regionIds,
                        excludeAgencies,
                        industryIds,
                        jobType,
                        jobHours,
                        keywords,
                        fromDate,
                        toDate,
                        startRecord,
                        pageSize,
                        key}, this.SearchJobsOperationCompleted, userState);
        }
        
        private void OnSearchJobsOperationCompleted(object arg) {
            if ((this.SearchJobsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchJobsCompleted(this, new SearchJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetJobDisplay", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JobDisplay GetJobDisplay(int jobId) {
            object[] results = this.Invoke("GetJobDisplay", new object[] {
                        jobId});
            return ((JobDisplay)(results[0]));
        }
        
        /// <remarks/>
        public void GetJobDisplayAsync(int jobId) {
            this.GetJobDisplayAsync(jobId, null);
        }
        
        /// <remarks/>
        public void GetJobDisplayAsync(int jobId, object userState) {
            if ((this.GetJobDisplayOperationCompleted == null)) {
                this.GetJobDisplayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobDisplayOperationCompleted);
            }
            this.InvokeAsync("GetJobDisplay", new object[] {
                        jobId}, this.GetJobDisplayOperationCompleted, userState);
        }
        
        private void OnGetJobDisplayOperationCompleted(object arg) {
            if ((this.GetJobDisplayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobDisplayCompleted(this, new GetJobDisplayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/ExpireJob", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExpireJob(string login, string password, int jobId) {
            object[] results = this.Invoke("ExpireJob", new object[] {
                        login,
                        password,
                        jobId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExpireJobAsync(string login, string password, int jobId) {
            this.ExpireJobAsync(login, password, jobId, null);
        }
        
        /// <remarks/>
        public void ExpireJobAsync(string login, string password, int jobId, object userState) {
            if ((this.ExpireJobOperationCompleted == null)) {
                this.ExpireJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExpireJobOperationCompleted);
            }
            this.InvokeAsync("ExpireJob", new object[] {
                        login,
                        password,
                        jobId}, this.ExpireJobOperationCompleted, userState);
        }
        
        private void OnExpireJobOperationCompleted(object arg) {
            if ((this.ExpireJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExpireJobCompleted(this, new ExpireJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/PostJob", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PostJob(string login, string password, Job job) {
            object[] results = this.Invoke("PostJob", new object[] {
                        login,
                        password,
                        job});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PostJobAsync(string login, string password, Job job) {
            this.PostJobAsync(login, password, job, null);
        }
        
        /// <remarks/>
        public void PostJobAsync(string login, string password, Job job, object userState) {
            if ((this.PostJobOperationCompleted == null)) {
                this.PostJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostJobOperationCompleted);
            }
            this.InvokeAsync("PostJob", new object[] {
                        login,
                        password,
                        job}, this.PostJobOperationCompleted, userState);
        }
        
        private void OnPostJobOperationCompleted(object arg) {
            if ((this.PostJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostJobCompleted(this, new PostJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/UpdateJob", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateJob(string login, string password, Job job) {
            this.Invoke("UpdateJob", new object[] {
                        login,
                        password,
                        job});
        }
        
        /// <remarks/>
        public void UpdateJobAsync(string login, string password, Job job) {
            this.UpdateJobAsync(login, password, job, null);
        }
        
        /// <remarks/>
        public void UpdateJobAsync(string login, string password, Job job, object userState) {
            if ((this.UpdateJobOperationCompleted == null)) {
                this.UpdateJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateJobOperationCompleted);
            }
            this.InvokeAsync("UpdateJob", new object[] {
                        login,
                        password,
                        job}, this.UpdateJobOperationCompleted, userState);
        }
        
        private void OnUpdateJobOperationCompleted(object arg) {
            if ((this.UpdateJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateJobCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/RefreshJob", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RefreshJob(string login, string password, int jobId) {
            object[] results = this.Invoke("RefreshJob", new object[] {
                        login,
                        password,
                        jobId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RefreshJobAsync(string login, string password, int jobId) {
            this.RefreshJobAsync(login, password, jobId, null);
        }
        
        /// <remarks/>
        public void RefreshJobAsync(string login, string password, int jobId, object userState) {
            if ((this.RefreshJobOperationCompleted == null)) {
                this.RefreshJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefreshJobOperationCompleted);
            }
            this.InvokeAsync("RefreshJob", new object[] {
                        login,
                        password,
                        jobId}, this.RefreshJobOperationCompleted, userState);
        }
        
        private void OnRefreshJobOperationCompleted(object arg) {
            if ((this.RefreshJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefreshJobCompleted(this, new RefreshJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/AddApplication", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddApplication(ApplicationData application) {
            object[] results = this.Invoke("AddApplication", new object[] {
                        application});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddApplicationAsync(ApplicationData application) {
            this.AddApplicationAsync(application, null);
        }
        
        /// <remarks/>
        public void AddApplicationAsync(ApplicationData application, object userState) {
            if ((this.AddApplicationOperationCompleted == null)) {
                this.AddApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddApplicationOperationCompleted);
            }
            this.InvokeAsync("AddApplication", new object[] {
                        application}, this.AddApplicationOperationCompleted, userState);
        }
        
        private void OnAddApplicationOperationCompleted(object arg) {
            if ((this.AddApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddApplicationCompleted(this, new AddApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetJobCategories", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public JobCategory[] GetJobCategories() {
            object[] results = this.Invoke("GetJobCategories", new object[0]);
            return ((JobCategory[])(results[0]));
        }
        
        /// <remarks/>
        public void GetJobCategoriesAsync() {
            this.GetJobCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetJobCategoriesAsync(object userState) {
            if ((this.GetJobCategoriesOperationCompleted == null)) {
                this.GetJobCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetJobCategories", new object[0], this.GetJobCategoriesOperationCompleted, userState);
        }
        
        private void OnGetJobCategoriesOperationCompleted(object arg) {
            if ((this.GetJobCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobCategoriesCompleted(this, new GetJobCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetIndustries", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Industry[] GetIndustries() {
            object[] results = this.Invoke("GetIndustries", new object[0]);
            return ((Industry[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndustriesAsync() {
            this.GetIndustriesAsync(null);
        }
        
        /// <remarks/>
        public void GetIndustriesAsync(object userState) {
            if ((this.GetIndustriesOperationCompleted == null)) {
                this.GetIndustriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndustriesOperationCompleted);
            }
            this.InvokeAsync("GetIndustries", new object[0], this.GetIndustriesOperationCompleted, userState);
        }
        
        private void OnGetIndustriesOperationCompleted(object arg) {
            if ((this.GetIndustriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndustriesCompleted(this, new GetIndustriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetJobRegions", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public JobRegion[] GetJobRegions() {
            object[] results = this.Invoke("GetJobRegions", new object[0]);
            return ((JobRegion[])(results[0]));
        }
        
        /// <remarks/>
        public void GetJobRegionsAsync() {
            this.GetJobRegionsAsync(null);
        }
        
        /// <remarks/>
        public void GetJobRegionsAsync(object userState) {
            if ((this.GetJobRegionsOperationCompleted == null)) {
                this.GetJobRegionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobRegionsOperationCompleted);
            }
            this.InvokeAsync("GetJobRegions", new object[0], this.GetJobRegionsOperationCompleted, userState);
        }
        
        private void OnGetJobRegionsOperationCompleted(object arg) {
            if ((this.GetJobRegionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobRegionsCompleted(this, new GetJobRegionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetCountries", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Country[] GetCountries() {
            object[] results = this.Invoke("GetCountries", new object[0]);
            return ((Country[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCountriesAsync() {
            this.GetCountriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCountriesAsync(object userState) {
            if ((this.GetCountriesOperationCompleted == null)) {
                this.GetCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountriesOperationCompleted);
            }
            this.InvokeAsync("GetCountries", new object[0], this.GetCountriesOperationCompleted, userState);
        }
        
        private void OnGetCountriesOperationCompleted(object arg) {
            if ((this.GetCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetAddressRegions", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AddressRegion[] GetAddressRegions() {
            object[] results = this.Invoke("GetAddressRegions", new object[0]);
            return ((AddressRegion[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressRegionsAsync() {
            this.GetAddressRegionsAsync(null);
        }
        
        /// <remarks/>
        public void GetAddressRegionsAsync(object userState) {
            if ((this.GetAddressRegionsOperationCompleted == null)) {
                this.GetAddressRegionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressRegionsOperationCompleted);
            }
            this.InvokeAsync("GetAddressRegions", new object[0], this.GetAddressRegionsOperationCompleted, userState);
        }
        
        private void OnGetAddressRegionsOperationCompleted(object arg) {
            if ((this.GetAddressRegionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressRegionsCompleted(this, new GetAddressRegionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.jobs.ie/webservices/GetEmployerStats", RequestNamespace="http://www.jobs.ie/webservices/", ResponseNamespace="http://www.jobs.ie/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmployerStats GetEmployerStats(string login, string password) {
            object[] results = this.Invoke("GetEmployerStats", new object[] {
                        login,
                        password});
            return ((EmployerStats)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployerStatsAsync(string login, string password) {
            this.GetEmployerStatsAsync(login, password, null);
        }
        
        /// <remarks/>
        public void GetEmployerStatsAsync(string login, string password, object userState) {
            if ((this.GetEmployerStatsOperationCompleted == null)) {
                this.GetEmployerStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployerStatsOperationCompleted);
            }
            this.InvokeAsync("GetEmployerStats", new object[] {
                        login,
                        password}, this.GetEmployerStatsOperationCompleted, userState);
        }
        
        private void OnGetEmployerStatsOperationCompleted(object arg) {
            if ((this.GetEmployerStatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployerStatsCompleted(this, new GetEmployerStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public enum JobDuration {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        Permanent,
        
        /// <remarks/>
        Contract,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public enum JobHours {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        FullTime,
        
        /// <remarks/>
        PartTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobListItem {
        
        private int idField;
        
        private System.DateTime createdDTField;
        
        private string titleField;
        
        private string companyField;
        
        private string locationField;
        
        private int employerIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDT {
            get {
                return this.createdDTField;
            }
            set {
                this.createdDTField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class EmployerStats {
        
        private int employerIdField;
        
        private int activeJobCountField;
        
        private int totalJobCountField;
        
        private int activeAdvertLimitField;
        
        private bool isSubscriptionEnabledField;
        
        /// <remarks/>
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
            }
        }
        
        /// <remarks/>
        public int ActiveJobCount {
            get {
                return this.activeJobCountField;
            }
            set {
                this.activeJobCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalJobCount {
            get {
                return this.totalJobCountField;
            }
            set {
                this.totalJobCountField = value;
            }
        }
        
        /// <remarks/>
        public int ActiveAdvertLimit {
            get {
                return this.activeAdvertLimitField;
            }
            set {
                this.activeAdvertLimitField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSubscriptionEnabled {
            get {
                return this.isSubscriptionEnabledField;
            }
            set {
                this.isSubscriptionEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class AddressRegion {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class Country {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobRegion {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class Industry {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobCategory {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class ApplicationData {
        
        private string coverNoteField;
        
        private string nameField;
        
        private string phoneField;
        
        private string emailField;
        
        private string answer1Field;
        
        private string answer2Field;
        
        private string answer3Field;
        
        private int jobIdField;
        
        private string cVFileNameField;
        
        private string cVFileTypeField;
        
        private byte[] cVFileDataField;
        
        /// <remarks/>
        public string CoverNote {
            get {
                return this.coverNoteField;
            }
            set {
                this.coverNoteField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Answer1 {
            get {
                return this.answer1Field;
            }
            set {
                this.answer1Field = value;
            }
        }
        
        /// <remarks/>
        public string Answer2 {
            get {
                return this.answer2Field;
            }
            set {
                this.answer2Field = value;
            }
        }
        
        /// <remarks/>
        public string Answer3 {
            get {
                return this.answer3Field;
            }
            set {
                this.answer3Field = value;
            }
        }
        
        /// <remarks/>
        public int JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        public string CVFileName {
            get {
                return this.cVFileNameField;
            }
            set {
                this.cVFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string CVFileType {
            get {
                return this.cVFileTypeField;
            }
            set {
                this.cVFileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CVFileData {
            get {
                return this.cVFileDataField;
            }
            set {
                this.cVFileDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class Job {
        
        private int idField;
        
        private string titleField;
        
        private string paymentField;
        
        private string locationField;
        
        private string descriptionField;
        
        private string htmlDescriptionField;
        
        private bool isFullTimeField;
        
        private bool isPartTimeField;
        
        private bool isPermanentField;
        
        private bool isContractField;
        
        private string question1Field;
        
        private string question2Field;
        
        private string question3Field;
        
        private string applicationURLField;
        
        private string[] contactEmailsField;
        
        private System.DateTime expiryDTField;
        
        private System.DateTime createdDTField;
        
        private System.DateTime modifiedDTField;
        
        private string referenceField;
        
        private int[] categoryIdsField;
        
        private int[] regionIdsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string HtmlDescription {
            get {
                return this.htmlDescriptionField;
            }
            set {
                this.htmlDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFullTime {
            get {
                return this.isFullTimeField;
            }
            set {
                this.isFullTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPartTime {
            get {
                return this.isPartTimeField;
            }
            set {
                this.isPartTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPermanent {
            get {
                return this.isPermanentField;
            }
            set {
                this.isPermanentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsContract {
            get {
                return this.isContractField;
            }
            set {
                this.isContractField = value;
            }
        }
        
        /// <remarks/>
        public string Question1 {
            get {
                return this.question1Field;
            }
            set {
                this.question1Field = value;
            }
        }
        
        /// <remarks/>
        public string Question2 {
            get {
                return this.question2Field;
            }
            set {
                this.question2Field = value;
            }
        }
        
        /// <remarks/>
        public string Question3 {
            get {
                return this.question3Field;
            }
            set {
                this.question3Field = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationURL {
            get {
                return this.applicationURLField;
            }
            set {
                this.applicationURLField = value;
            }
        }
        
        /// <remarks/>
        public string[] ContactEmails {
            get {
                return this.contactEmailsField;
            }
            set {
                this.contactEmailsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryDT {
            get {
                return this.expiryDTField;
            }
            set {
                this.expiryDTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDT {
            get {
                return this.createdDTField;
            }
            set {
                this.createdDTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDT {
            get {
                return this.modifiedDTField;
            }
            set {
                this.modifiedDTField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public int[] CategoryIds {
            get {
                return this.categoryIdsField;
            }
            set {
                this.categoryIdsField = value;
            }
        }
        
        /// <remarks/>
        public int[] RegionIds {
            get {
                return this.regionIdsField;
            }
            set {
                this.regionIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jobs.ie/webservices/")]
    public partial class JobDisplay {
        
        private int idField;
        
        private int employerIdField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string htmlDescriptionField;
        
        private string locationField;
        
        private string paymentField;
        
        private string referenceField;
        
        private System.DateTime modifiedDTField;
        
        private System.DateTime createdDTField;
        
        private string applicationURLField;
        
        private string question1Field;
        
        private string question2Field;
        
        private string question3Field;
        
        private bool isFullTimeField;
        
        private bool isPartTimeField;
        
        private bool isPermanentField;
        
        private bool isContractField;
        
        private bool hasLogoField;
        
        private string homepageUrlField;
        
        private string companyField;
        
        private string addressField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string contactField;
        
        private string[] categoryNamesField;
        
        private string[] regionNamesField;
        
        private int[] categoryIdsField;
        
        private int[] regionIdsField;
        
        private bool isContactHiddenField;
        
        private bool isCompanyNameHiddenField;
        
        private bool isEmailHiddenField;
        
        private bool isPhoneHiddenField;
        
        private bool isFaxHiddenField;
        
        private bool isAddressHiddenField;
        
        private bool isHomePageHiddenField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int EmployerId {
            get {
                return this.employerIdField;
            }
            set {
                this.employerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string HtmlDescription {
            get {
                return this.htmlDescriptionField;
            }
            set {
                this.htmlDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDT {
            get {
                return this.modifiedDTField;
            }
            set {
                this.modifiedDTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDT {
            get {
                return this.createdDTField;
            }
            set {
                this.createdDTField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationURL {
            get {
                return this.applicationURLField;
            }
            set {
                this.applicationURLField = value;
            }
        }
        
        /// <remarks/>
        public string Question1 {
            get {
                return this.question1Field;
            }
            set {
                this.question1Field = value;
            }
        }
        
        /// <remarks/>
        public string Question2 {
            get {
                return this.question2Field;
            }
            set {
                this.question2Field = value;
            }
        }
        
        /// <remarks/>
        public string Question3 {
            get {
                return this.question3Field;
            }
            set {
                this.question3Field = value;
            }
        }
        
        /// <remarks/>
        public bool IsFullTime {
            get {
                return this.isFullTimeField;
            }
            set {
                this.isFullTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPartTime {
            get {
                return this.isPartTimeField;
            }
            set {
                this.isPartTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPermanent {
            get {
                return this.isPermanentField;
            }
            set {
                this.isPermanentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsContract {
            get {
                return this.isContractField;
            }
            set {
                this.isContractField = value;
            }
        }
        
        /// <remarks/>
        public bool HasLogo {
            get {
                return this.hasLogoField;
            }
            set {
                this.hasLogoField = value;
            }
        }
        
        /// <remarks/>
        public string HomepageUrl {
            get {
                return this.homepageUrlField;
            }
            set {
                this.homepageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string[] CategoryNames {
            get {
                return this.categoryNamesField;
            }
            set {
                this.categoryNamesField = value;
            }
        }
        
        /// <remarks/>
        public string[] RegionNames {
            get {
                return this.regionNamesField;
            }
            set {
                this.regionNamesField = value;
            }
        }
        
        /// <remarks/>
        public int[] CategoryIds {
            get {
                return this.categoryIdsField;
            }
            set {
                this.categoryIdsField = value;
            }
        }
        
        /// <remarks/>
        public int[] RegionIds {
            get {
                return this.regionIdsField;
            }
            set {
                this.regionIdsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsContactHidden {
            get {
                return this.isContactHiddenField;
            }
            set {
                this.isContactHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCompanyNameHidden {
            get {
                return this.isCompanyNameHiddenField;
            }
            set {
                this.isCompanyNameHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEmailHidden {
            get {
                return this.isEmailHiddenField;
            }
            set {
                this.isEmailHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPhoneHidden {
            get {
                return this.isPhoneHiddenField;
            }
            set {
                this.isPhoneHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFaxHidden {
            get {
                return this.isFaxHiddenField;
            }
            set {
                this.isFaxHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAddressHidden {
            get {
                return this.isAddressHiddenField;
            }
            set {
                this.isAddressHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHomePageHidden {
            get {
                return this.isHomePageHiddenField;
            }
            set {
                this.isHomePageHiddenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SearchJobsCompletedEventHandler(object sender, SearchJobsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobListItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobListItem[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int recordCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetJobDisplayCompletedEventHandler(object sender, GetJobDisplayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobDisplayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobDisplayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobDisplay Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobDisplay)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExpireJobCompletedEventHandler(object sender, ExpireJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExpireJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExpireJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostJobCompletedEventHandler(object sender, PostJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateJobCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RefreshJobCompletedEventHandler(object sender, RefreshJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefreshJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefreshJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddApplicationCompletedEventHandler(object sender, AddApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetJobCategoriesCompletedEventHandler(object sender, GetJobCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobCategory[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobCategory[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetIndustriesCompletedEventHandler(object sender, GetIndustriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndustriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndustriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Industry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Industry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetJobRegionsCompletedEventHandler(object sender, GetJobRegionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobRegionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobRegionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobRegion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobRegion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCountriesCompletedEventHandler(object sender, GetCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Country[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Country[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAddressRegionsCompletedEventHandler(object sender, GetAddressRegionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressRegionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressRegionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressRegion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressRegion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetEmployerStatsCompletedEventHandler(object sender, GetEmployerStatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployerStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployerStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmployerStats Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmployerStats)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591